// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../../pkg/vault/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @param {vault$0.VaultEntry} entry
 * @returns {$CancellablePromise<$models.EntryMutationResult | null>}
 */
export function AddEntry(path, entry) {
    return $Call.ByID(1742439231, path, entry).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {string} id
 * @returns {$CancellablePromise<$models.EntryDeletionResult | null>}
 */
export function DeleteEntry(path, id) {
    return $Call.ByID(1512471043, path, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} path
 * @param {string} id
 * @returns {$CancellablePromise<vault$0.Trash>}
 */
export function DeleteTrashEntry(path, id) {
    return $Call.ByID(1227693219, path, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<vault$0.VaultEntry[]>}
 */
export function ListEntries(path) {
    return $Call.ByID(3849911718, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<vault$0.Trash>}
 */
export function ListTrash(path) {
    return $Call.ByID(750454476, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @param {string} id
 * @returns {$CancellablePromise<$models.TrashMutationResult | null>}
 */
export function RestoreTrashEntry(path, id) {
    return $Call.ByID(734920722, path, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} path
 * @param {vault$0.VaultEntry} entry
 * @returns {$CancellablePromise<$models.EntryMutationResult | null>}
 */
export function UpdateEntry(path, entry) {
    return $Call.ByID(1569198237, path, entry).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.EntryMutationResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.EntryDeletionResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = vault$0.Trash.createFrom;
const $$createType5 = vault$0.VaultEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.TrashMutationResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
