// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../../pkg/vault/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @param {vault$0.Group} group
 * @returns {$CancellablePromise<vault$0.Group[]>}
 */
export function AddGroup(path, group) {
    return $Call.ByID(1089309371, path, group).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {string} tag
 * @returns {$CancellablePromise<string[]>}
 */
export function AddTag(path, tag) {
    return $Call.ByID(4049252616, path, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} sourcePath
 * @param {string} targetPath
 * @param {string} groupID
 * @param {string} targetGroupID
 * @returns {$CancellablePromise<[vault$0.Group[], vault$0.VaultEntry[]]>}
 */
export function CopyGroupToVault(sourcePath, targetPath, groupID, targetGroupID) {
    return $Call.ByID(2946981178, sourcePath, targetPath, groupID, targetGroupID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType4($result[1]);
        return $result;
    }));
}

/**
 * @param {string} path
 * @param {string} groupID
 * @returns {$CancellablePromise<$models.GroupDeletionResult | null>}
 */
export function DeleteGroup(path, groupID) {
    return $Call.ByID(2519229897, path, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<vault$0.Group[]>}
 */
export function ListGroups(path) {
    return $Call.ByID(163629509, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {string} sourceID
 * @param {string} targetID
 * @returns {$CancellablePromise<[vault$0.Group[], vault$0.VaultEntry[]]>}
 */
export function MergeGroups(path, sourceID, targetID) {
    return $Call.ByID(2320380211, path, sourceID, targetID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType4($result[1]);
        return $result;
    }));
}

/**
 * @param {string} path
 * @param {string} groupID
 * @param {string | null} newParentID
 * @returns {$CancellablePromise<vault$0.Group[]>}
 */
export function MoveGroupToParent(path, groupID, newParentID) {
    return $Call.ByID(3697675102, path, groupID, newParentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sourcePath
 * @param {string} targetPath
 * @param {string} groupID
 * @param {string} targetGroupID
 * @returns {$CancellablePromise<$models.MoveGroupToVaultResult | null>}
 */
export function MoveGroupToVault(sourcePath, targetPath, groupID, targetGroupID) {
    return $Call.ByID(1934247490, sourcePath, targetPath, groupID, targetGroupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} path
 * @param {vault$0.Group[]} groups
 * @returns {$CancellablePromise<vault$0.Group[]>}
 */
export function ReorderGroups(path, groups) {
    return $Call.ByID(663861844, path, groups).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = vault$0.Group.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = vault$0.VaultEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.GroupDeletionResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.MoveGroupToVaultResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
