// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../../pkg/vault/models.js";

export class EntryDeletionResult {
    /**
     * Creates a new EntryDeletionResult instance.
     * @param {Partial<EntryDeletionResult>} [$$source = {}] - The source object to create the EntryDeletionResult.
     */
    constructor($$source = {}) {
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry[]}
             */
            this["entries"] = [];
        }
        if (!("trash" in $$source)) {
            /**
             * @member
             * @type {vault$0.Trash}
             */
            this["trash"] = (new vault$0.Trash());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryDeletionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryDeletionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        if ("trash" in $$parsedSource) {
            $$parsedSource["trash"] = $$createField1_0($$parsedSource["trash"]);
        }
        return new EntryDeletionResult(/** @type {Partial<EntryDeletionResult>} */($$parsedSource));
    }
}

export class EntryMutationResult {
    /**
     * Creates a new EntryMutationResult instance.
     * @param {Partial<EntryMutationResult>} [$$source = {}] - The source object to create the EntryMutationResult.
     */
    constructor($$source = {}) {
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry}
             */
            this["entry"] = (new vault$0.VaultEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryMutationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryMutationResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField0_0($$parsedSource["entry"]);
        }
        return new EntryMutationResult(/** @type {Partial<EntryMutationResult>} */($$parsedSource));
    }
}

export class GroupDeletionResult {
    /**
     * Creates a new GroupDeletionResult instance.
     * @param {Partial<GroupDeletionResult>} [$$source = {}] - The source object to create the GroupDeletionResult.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {vault$0.Group[]}
             */
            this["groups"] = [];
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry[]}
             */
            this["entries"] = [];
        }
        if (!("trash" in $$source)) {
            /**
             * @member
             * @type {vault$0.Trash}
             */
            this["trash"] = (new vault$0.Trash());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupDeletionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupDeletionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        if ("trash" in $$parsedSource) {
            $$parsedSource["trash"] = $$createField2_0($$parsedSource["trash"]);
        }
        return new GroupDeletionResult(/** @type {Partial<GroupDeletionResult>} */($$parsedSource));
    }
}

export class MoveGroupToVaultResult {
    /**
     * Creates a new MoveGroupToVaultResult instance.
     * @param {Partial<MoveGroupToVaultResult>} [$$source = {}] - The source object to create the MoveGroupToVaultResult.
     */
    constructor($$source = {}) {
        if (!("source_groups" in $$source)) {
            /**
             * @member
             * @type {vault$0.Group[]}
             */
            this["source_groups"] = [];
        }
        if (!("source_entries" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry[]}
             */
            this["source_entries"] = [];
        }
        if (!("target_groups" in $$source)) {
            /**
             * @member
             * @type {vault$0.Group[]}
             */
            this["target_groups"] = [];
        }
        if (!("target_entries" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry[]}
             */
            this["target_entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveGroupToVaultResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveGroupToVaultResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_groups" in $$parsedSource) {
            $$parsedSource["source_groups"] = $$createField0_0($$parsedSource["source_groups"]);
        }
        if ("source_entries" in $$parsedSource) {
            $$parsedSource["source_entries"] = $$createField1_0($$parsedSource["source_entries"]);
        }
        if ("target_groups" in $$parsedSource) {
            $$parsedSource["target_groups"] = $$createField2_0($$parsedSource["target_groups"]);
        }
        if ("target_entries" in $$parsedSource) {
            $$parsedSource["target_entries"] = $$createField3_0($$parsedSource["target_entries"]);
        }
        return new MoveGroupToVaultResult(/** @type {Partial<MoveGroupToVaultResult>} */($$parsedSource));
    }
}

export class PasswordOptions {
    /**
     * Creates a new PasswordOptions instance.
     * @param {Partial<PasswordOptions>} [$$source = {}] - The source object to create the PasswordOptions.
     */
    constructor($$source = {}) {
        if (!("length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }
        if (!("uppercase" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["uppercase"] = false;
        }
        if (!("lowercase" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lowercase"] = false;
        }
        if (!("digits" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["digits"] = false;
        }
        if (!("space" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["space"] = false;
        }
        if (!("underscore_dash" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["underscore_dash"] = false;
        }
        if (!("symbols" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["symbols"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasswordOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PasswordOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PasswordOptions(/** @type {Partial<PasswordOptions>} */($$parsedSource));
    }
}

export class TrashMutationResult {
    /**
     * Creates a new TrashMutationResult instance.
     * @param {Partial<TrashMutationResult>} [$$source = {}] - The source object to create the TrashMutationResult.
     */
    constructor($$source = {}) {
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["group_id"] = null;
        }
        if (!("group_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_name"] = "";
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {vault$0.Group[]}
             */
            this["groups"] = [];
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {vault$0.VaultEntry[]}
             */
            this["entries"] = [];
        }
        if (!("trash" in $$source)) {
            /**
             * @member
             * @type {vault$0.Trash}
             */
            this["trash"] = (new vault$0.Trash());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashMutationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrashMutationResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        if ("trash" in $$parsedSource) {
            $$parsedSource["trash"] = $$createField4_0($$parsedSource["trash"]);
        }
        return new TrashMutationResult(/** @type {Partial<TrashMutationResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = vault$0.VaultEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = vault$0.Trash.createFrom;
const $$createType3 = vault$0.Group.createFrom;
const $$createType4 = $Create.Array($$createType3);
