// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../../pkg/vault/models.js";

/**
 * @param {string} path
 * @param {string} password
 * @param {string} newLevel
 * @returns {$CancellablePromise<void>}
 */
export function ChangeSecurityLevel(path, password, newLevel) {
    return $Call.ByID(3830876166, path, password, newLevel);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function CloseVault(path) {
    return $Call.ByID(2644514618, path);
}

/**
 * @param {string} bcupPath
 * @param {string} password
 * @param {string} outputPath
 * @param {string} id
 * @param {string | null} securityLevel
 * @returns {$CancellablePromise<vault$0.VaultFileDTO | null>}
 */
export function ConvertButtercupVault(bcupPath, password, outputPath, id, securityLevel) {
    return $Call.ByID(2266265383, bcupPath, password, outputPath, id, securityLevel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} kdbxPath
 * @param {string} password
 * @param {string} outputPath
 * @param {string} id
 * @param {string | null} securityLevel
 * @returns {$CancellablePromise<vault$0.VaultFileDTO | null>}
 */
export function ConvertKeepassVault(kdbxPath, password, outputPath, id, securityLevel) {
    return $Call.ByID(1004863015, kdbxPath, password, outputPath, id, securityLevel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string} path
 * @param {string} password
 * @param {string | null} securityLevel
 * @returns {$CancellablePromise<config$0.VaultConfig | null>}
 */
export function CreateVault(id, name, path, password, securityLevel) {
    return $Call.ByID(2949277794, id, name, path, password, securityLevel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVault(id, path) {
    return $Call.ByID(2145669519, id, path);
}

/**
 * @returns {$CancellablePromise<config$0.AppConfig | null>}
 */
export function ListVaults() {
    return $Call.ByID(589029595).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} path
 * @param {string} password
 * @returns {$CancellablePromise<vault$0.VaultFileDTO | null>}
 */
export function OpenVault(path, password) {
    return $Call.ByID(116743118, path, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} path
 * @param {string} password
 * @returns {$CancellablePromise<vault$0.VaultFileDTO | null>}
 */
export function RegisterAndOpenVault(id, path, password) {
    return $Call.ByID(656572224, id, path, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<config$0.VaultConfig | null>}
 */
export function RenameVault(id, name) {
    return $Call.ByID(209057456, id, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<config$0.VaultConfig[]>}
 */
export function ReorderVaults(ids) {
    return $Call.ByID(1810584568, ids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = vault$0.VaultFileDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.VaultConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.AppConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType2);
