// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CustomField {
    /**
     * Creates a new CustomField instance.
     * @param {Partial<CustomField>} [$$source = {}] - The source object to create the CustomField.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomField}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomField(/** @type {Partial<CustomField>} */($$parsedSource));
    }
}

export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["parent_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

export class HistoryItem {
    /**
     * Creates a new HistoryItem instance.
     * @param {Partial<HistoryItem>} [$$source = {}] - The source object to create the HistoryItem.
     */
    constructor($$source = {}) {
        if (!("property" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["property"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updated_at"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryItem}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updated_at" in $$parsedSource) {
            $$parsedSource["updated_at"] = $$createField2_0($$parsedSource["updated_at"]);
        }
        return new HistoryItem(/** @type {Partial<HistoryItem>} */($$parsedSource));
    }
}

export class Trash {
    /**
     * Creates a new Trash instance.
     * @param {Partial<Trash>} [$$source = {}] - The source object to create the Trash.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {Group[]}
             */
            this["groups"] = [];
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {VaultEntry[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Trash instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Trash}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new Trash(/** @type {Partial<Trash>} */($$parsedSource));
    }
}

export class VaultEntry {
    /**
     * Creates a new VaultEntry instance.
     * @param {Partial<VaultEntry>} [$$source = {}] - The source object to create the VaultEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {CustomField[]}
             */
            this["fields"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["group_id"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["created_at"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updated_at"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Date | null | undefined}
             */
            this["deleted_at"] = undefined;
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {HistoryItem[]}
             */
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultEntry}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        const $$createField7_0 = $Create.DateFromTime;
        const $$createField8_0 = $Create.DateFromTime;
        const $$createField9_0 = $$createType7;
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField5_0($$parsedSource["fields"]);
        }
        if ("created_at" in $$parsedSource) {
            $$parsedSource["created_at"] = $$createField7_0($$parsedSource["created_at"]);
        }
        if ("updated_at" in $$parsedSource) {
            $$parsedSource["updated_at"] = $$createField8_0($$parsedSource["updated_at"]);
        }
        if ("deleted_at" in $$parsedSource) {
            $$parsedSource["deleted_at"] = $$createField9_0($$parsedSource["deleted_at"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField10_0($$parsedSource["history"]);
        }
        return new VaultEntry(/** @type {Partial<VaultEntry>} */($$parsedSource));
    }
}

/**
 * VaultFileDTO is the serializable representation sent to the frontend.
 */
export class VaultFileDTO {
    /**
     * Creates a new VaultFileDTO instance.
     * @param {Partial<VaultFileDTO>} [$$source = {}] - The source object to create the VaultFileDTO.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {Group[]}
             */
            this["groups"] = [];
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {VaultEntry[]}
             */
            this["entries"] = [];
        }
        if (!("trash" in $$source)) {
            /**
             * @member
             * @type {Trash}
             */
            this["trash"] = (new Trash());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultFileDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultFileDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField4_0($$parsedSource["entries"]);
        }
        if ("trash" in $$parsedSource) {
            $$parsedSource["trash"] = $$createField5_0($$parsedSource["trash"]);
        }
        return new VaultFileDTO(/** @type {Partial<VaultFileDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Group.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = VaultEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = CustomField.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Nullable($Create.DateFromTime);
const $$createType8 = HistoryItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Trash.createFrom;
