// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("vaults" in $$source)) {
            /**
             * @member
             * @type {VaultConfig[]}
             */
            this["vaults"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("vaults" in $$parsedSource) {
            $$parsedSource["vaults"] = $$createField0_0($$parsedSource["vaults"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class VaultConfig {
    /**
     * Creates a new VaultConfig instance.
     * @param {Partial<VaultConfig>} [$$source = {}] - The source object to create the VaultConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultConfig(/** @type {Partial<VaultConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VaultConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
